name: logger_view
description: Flutter extension to logger to show logs easily shile debugging
version: 0.0.1

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  logger: ^1.1.0
  sensors_plus: ^1.3.1
  share_plus: ^4.0.4
  path_provider: ^2.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.8.2
